/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ProductStatusEnum = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  OUTDATE: 'OUTDATE'
} as const

export type ProductStatusEnum = (typeof ProductStatusEnum)[keyof typeof ProductStatusEnum]


export const OfferPaymentMethod = {
  CREDIT_CARD: 'CREDIT_CARD',
  PIX: 'PIX'
} as const

export type OfferPaymentMethod = (typeof OfferPaymentMethod)[keyof typeof OfferPaymentMethod]
