/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Category'
export type * from './models/Brand'
export type * from './models/Color'
export type * from './models/Tag'
export type * from './models/Product'
export type * from './models/Kind'
export type * from './models/Image'
export type * from './models/Offer'
export type * from './commonInputTypes'