/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Category: 'Category',
  Brand: 'Brand',
  Color: 'Color',
  Tag: 'Tag',
  Product: 'Product',
  Kind: 'Kind',
  Image: 'Image',
  Offer: 'Offer'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CategoryScalarFieldEnum = {
  id: 'id',
  createAt: 'createAt',
  slug: 'slug',
  code: 'code',
  title: 'title',
  description: 'description',
  parentId: 'parentId'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const BrandScalarFieldEnum = {
  id: 'id',
  createAt: 'createAt',
  slug: 'slug',
  code: 'code',
  title: 'title',
  description: 'description'
} as const

export type BrandScalarFieldEnum = (typeof BrandScalarFieldEnum)[keyof typeof BrandScalarFieldEnum]


export const ColorScalarFieldEnum = {
  id: 'id',
  createAt: 'createAt',
  slug: 'slug',
  code: 'code',
  colorHex: 'colorHex',
  title: 'title',
  description: 'description'
} as const

export type ColorScalarFieldEnum = (typeof ColorScalarFieldEnum)[keyof typeof ColorScalarFieldEnum]


export const TagScalarFieldEnum = {
  id: 'id',
  createAt: 'createAt',
  label: 'label',
  slug: 'slug'
} as const

export type TagScalarFieldEnum = (typeof TagScalarFieldEnum)[keyof typeof TagScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  createAt: 'createAt',
  slug: 'slug',
  barcode: 'barcode',
  sku: 'sku',
  model: 'model',
  title: 'title',
  description: 'description',
  content: 'content',
  stock: 'stock',
  height: 'height',
  length: 'length',
  weight: 'weight',
  width: 'width',
  status: 'status',
  parentId: 'parentId',
  brandId: 'brandId',
  categoryId: 'categoryId',
  colorId: 'colorId',
  kindId: 'kindId'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const KindScalarFieldEnum = {
  id: 'id',
  createAt: 'createAt',
  code: 'code',
  label: 'label'
} as const

export type KindScalarFieldEnum = (typeof KindScalarFieldEnum)[keyof typeof KindScalarFieldEnum]


export const ImageScalarFieldEnum = {
  id: 'id',
  createAt: 'createAt',
  filename: 'filename',
  ext: 'ext',
  description: 'description',
  productId: 'productId'
} as const

export type ImageScalarFieldEnum = (typeof ImageScalarFieldEnum)[keyof typeof ImageScalarFieldEnum]


export const OfferScalarFieldEnum = {
  id: 'id',
  createAt: 'createAt',
  price: 'price',
  promotionalPrice: 'promotionalPrice',
  discount: 'discount',
  paymentMethods: 'paymentMethods',
  isActive: 'isActive',
  productId: 'productId'
} as const

export type OfferScalarFieldEnum = (typeof OfferScalarFieldEnum)[keyof typeof OfferScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

